### ISSUE TITLE
feat: Improve OpenAI Coverage dashboard

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex-web#17]
p2: For next iteration: 

1. Overing over each tile shows 
```
passing: 100
failing: 100
```

2. Click on each tile takes us to the specifc set of tests 
3. Sort /endpoints aphabetically

![image](https://github.com/janhq/cortex-web/assets/69952136/cd15fc3e-413c-457c-9bf0-9db92f5cd53f)

**Comment by Van-QA** [comment]
As discussed, No. 2 will not be included in scope because it requires a lot of work and is difficult to implement for the Eng team. Instead, please visit the Report Portal directly.
Cc: @0xSage
