### ISSUE TITLE
docs: Add other model format's `model.yamls` to model-operations page

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex-web#46]
https://dd1e7f4c.cortex-docs.pages.dev/docs/model-operations

- [x] GGUF
- [x] ONNX
- [x] Tensorrt-LLM

We can use the horizontal tabs to do it, instead of separate headings.

**Comment by irfanpena** [comment]
https://github.com/janhq/cortex-web/pull/57
https://github.com/janhq/cortex-web/pull/54

**Comment by irfanpena** [comment]
@0xSage Thank you for helping with the documentation.
